openapi: 3.0.3
info:
  title: Prices API Specification
  description: |-
    A simple pricing API that allows to obtain
    the price of a product given its id, brand and
    a date.
  version: 1.0.0-SNAPSHOT
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: prices
    description: Operations related to prices
paths:
  /prices/{productId}/{brandId}/{date}:
    get:
      tags:
        - prices
      summary: Get the price of a product
      description: |-
        Returns the price of a product given its id, brand and date.
      operationId: getPrice
      parameters:
        - name: productId
          in: path
          description: The id of the product
          required: true
          schema:
            type: integer
            format: int64
        - name: brandId
          in: path
          description: The id of the brand
          required: true
          schema:
            type: integer
            format: int64
        - name: date
          in: path
          description: The date to get the price
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: The price of the product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price' 
        '400':
          description: Invalid input
        '404':
          description: Product not found
        '500':
          description: Internal server error
components:
  schemas:
    Price:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        currency:
          type: string
        price:
          type: number
          format: double
